name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Great Work. Just make sure you have followed the issue format correctly. Good day :smile:'' first issue'
        pr-message: 'Thank you for resolving the task/error! The maintainers are on their way to see your wonderful contribution. Sit back, we will let you know. :smile: :smile:'' first pr'
